### ISSUE TITLE
Develop R script to translate existing rulesets into spreadsheet format

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/record-cleaner-rules#5]
@robin-hutchinson to work on R script

**Comment by JimBacon** [comment]
Hi @robin-hutchinson. In addressing #6, I observe that the existing spreadsheet format (actually a collection of spreadsheets) appears to have been written for the convenience of the R scripts rather than for the humans that have to create/edit the information.

I wonder if we could do better, making the scripts work a little harder so the humans can have an easier time. That said, something like the tenkm rules may be machine generated anyway. Have a think.

**Comment by robin-hutchinson** [comment]
Hi @JimBacon that is a good point - I will have a look at what I can do with the R scripts to make the initial conversion into something more user friendly, and then go back to the R scripts running excel -> txt file so that they still work!

**Comment by robin-hutchinson** [comment]
I've added the script to the txt_to_csv branch now, along with some examples of the csvs it produces - I'm not sure how to make the tenkm csv more user-friendly without it being a map? For the "General" csvs, I think it would be useful to also provide a guide to editing it, including what the options are within each column, and the comment that would appear to the recorder if they triggered the cleaner?

Let me know if you'd like me to make any changes to the format for recording schemes, and I can work on the code to turn this into the format that the csv -> txt script wants.

**Comment by robin-hutchinson** [comment]
All files in csv - will create new issue for csv -> txt
